name: flutter_json_deep_search
description: A powerful and flexible Flutter package for deep searching within JSON data structures.
version: 1.0.1
homepage: https://github.com/wanmind-innovation/flutter_json_deep_search
repository: https://github.com/wanmind-innovation/flutter_json_deep_search
example:
  path: example

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
